#!/bin/bash
#PBS -N Re10000
#PBS -l select=1:ncpus=1:ngpus=1:mem=30gb
#PBS -l walltime=24:00:00

#NOTE: do hlavicky lze jeste pridat napr. :cluster=bee, mozna upravit 
wall time)
#NOTE: Uprav cestu na vlastni slozku s tnl a instalaci tnlcxx, viz 
navod pripojeni-na-metacentrum.md

module load cuda/12.6.1-gcc-10.2.1-hplxoqp
export 
PATH="/storage/praha1/home/haladto1/resources/cmake-3.31.9/build/bin:$PATH"
export PATH="/storage/brno2/home/haladto1/playground/tnlcxx:$PATH"

export 
CMAKE_PREFIX_PATH=/storage/brno2/home/haladto1/playground/my-tnl-installation/lib/cmake/TNL:$CMAKE_PREFIX_PATH
export 
CMAKE_PREFIX_PATH=/cvmfs/software.metacentrum.cz/spack18/software/linux-debian11-x86_64_v2/gcc-10.2.1/cuda-12.6.1-hplxoqpnmn7k5zolkvqlaxndmpd5s3ft/targets/x86_64-linux/lib/cmake:$CMAKE_PREFIX_PATH

#NOTE: prekompiluj a pust example

cd /uplna/cesta/na/slozku/s/danym/RE
tnlcxx main.cu
./main
